<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PhoneCountryCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['country_name' => 'Afghanistan', 'phone_country_code' => '+93'],
            ['country_name' => 'Albania', 'phone_country_code' => '+355'],
            ['country_name' => 'Algeria', 'phone_country_code' => '+213'],
            ['country_name' => 'Andorra', 'phone_country_code' => '+376'],
            ['country_name' => 'Angola', 'phone_country_code' => '+244'],
            ['country_name' => 'Argentina', 'phone_country_code' => '+54'],
            ['country_name' => 'Armenia', 'phone_country_code' => '+374'],
            ['country_name' => 'Australia', 'phone_country_code' => '+61'],
            ['country_name' => 'Austria', 'phone_country_code' => '+43'],
            ['country_name' => 'Azerbaijan', 'phone_country_code' => '+994'],
            ['country_name' => 'Bahrain', 'phone_country_code' => '+973'],
            ['country_name' => 'Bangladesh', 'phone_country_code' => '+880'],
            ['country_name' => 'Belarus', 'phone_country_code' => '+375'],
            ['country_name' => 'Belgium', 'phone_country_code' => '+32'],
            ['country_name' => 'Belize', 'phone_country_code' => '+501'],
            ['country_name' => 'Benin', 'phone_country_code' => '+229'],
            ['country_name' => 'Bhutan', 'phone_country_code' => '+975'],
            ['country_name' => 'Bolivia', 'phone_country_code' => '+591'],
            ['country_name' => 'Bosnia and Herzegovina', 'phone_country_code' => '+387'],
            ['country_name' => 'Botswana', 'phone_country_code' => '+267'],
            ['country_name' => 'Brazil', 'phone_country_code' => '+55'],
            ['country_name' => 'Brunei', 'phone_country_code' => '+673'],
            ['country_name' => 'Bulgaria', 'phone_country_code' => '+359'],
            ['country_name' => 'Burkina Faso', 'phone_country_code' => '+226'],
            ['country_name' => 'Burundi', 'phone_country_code' => '+257'],
            ['country_name' => 'Cambodia', 'phone_country_code' => '+855'],
            ['country_name' => 'Cameroon', 'phone_country_code' => '+237'],
            ['country_name' => 'Canada', 'phone_country_code' => '+1'],
            ['country_name' => 'Cape Verde', 'phone_country_code' => '+238'],
            ['country_name' => 'Central African Republic', 'phone_country_code' => '+236'],
            ['country_name' => 'Chad', 'phone_country_code' => '+235'],
            ['country_name' => 'Chile', 'phone_country_code' => '+56'],
            ['country_name' => 'China', 'phone_country_code' => '+86'],
            ['country_name' => 'Colombia', 'phone_country_code' => '+57'],
            ['country_name' => 'Comoros', 'phone_country_code' => '+269'],
            ['country_name' => 'Costa Rica', 'phone_country_code' => '+506'],
            ['country_name' => 'Croatia', 'phone_country_code' => '+385'],
            ['country_name' => 'Cuba', 'phone_country_code' => '+53'],
            ['country_name' => 'Cyprus', 'phone_country_code' => '+357'],
            ['country_name' => 'Czech Republic', 'phone_country_code' => '+420'],
            ['country_name' => 'Denmark', 'phone_country_code' => '+45'],
            ['country_name' => 'Djibouti', 'phone_country_code' => '+253'],
            ['country_name' => 'Dominican Republic', 'phone_country_code' => '+1'],
            ['country_name' => 'Ecuador', 'phone_country_code' => '+593'],
            ['country_name' => 'Egypt', 'phone_country_code' => '+20'],
            ['country_name' => 'El Salvador', 'phone_country_code' => '+503'],
            ['country_name' => 'Equatorial Guinea', 'phone_country_code' => '+240'],
            ['country_name' => 'Eritrea', 'phone_country_code' => '+291'],
            ['country_name' => 'Estonia', 'phone_country_code' => '+372'],
            ['country_name' => 'Ethiopia', 'phone_country_code' => '+251'],
            ['country_name' => 'Fiji', 'phone_country_code' => '+679'],
            ['country_name' => 'Finland', 'phone_country_code' => '+358'],
            ['country_name' => 'France', 'phone_country_code' => '+33'],
            ['country_name' => 'Gabon', 'phone_country_code' => '+241'],
            ['country_name' => 'Gambia', 'phone_country_code' => '+220'],
            ['country_name' => 'Georgia', 'phone_country_code' => '+995'],
            ['country_name' => 'Germany', 'phone_country_code' => '+49'],
            ['country_name' => 'Ghana', 'phone_country_code' => '+233'],
            ['country_name' => 'Greece', 'phone_country_code' => '+30'],
            ['country_name' => 'Guatemala', 'phone_country_code' => '+502'],
            ['country_name' => 'Guinea', 'phone_country_code' => '+224'],
            ['country_name' => 'Guinea-Bissau', 'phone_country_code' => '+245'],
            ['country_name' => 'Guyana', 'phone_country_code' => '+592'],
            ['country_name' => 'Haiti', 'phone_country_code' => '+509'],
            ['country_name' => 'Honduras', 'phone_country_code' => '+504'],
            ['country_name' => 'Hong Kong', 'phone_country_code' => '+852'],
            ['country_name' => 'Hungary', 'phone_country_code' => '+36'],
            ['country_name' => 'Iceland', 'phone_country_code' => '+354'],
            ['country_name' => 'India', 'phone_country_code' => '+91'],
            ['country_name' => 'Indonesia', 'phone_country_code' => '+62'],
            ['country_name' => 'Iran', 'phone_country_code' => '+98'],
            ['country_name' => 'Iraq', 'phone_country_code' => '+964'],
            ['country_name' => 'Ireland', 'phone_country_code' => '+353'],
            ['country_name' => 'Israel', 'phone_country_code' => '+972'],
            ['country_name' => 'Italy', 'phone_country_code' => '+39'],
            ['country_name' => 'Jamaica', 'phone_country_code' => '+1'],
            ['country_name' => 'Japan', 'phone_country_code' => '+81'],
            ['country_name' => 'Jordan', 'phone_country_code' => '+962'],
            ['country_name' => 'Kazakhstan', 'phone_country_code' => '+7'],
            ['country_name' => 'Kenya', 'phone_country_code' => '+254'],
            ['country_name' => 'Kuwait', 'phone_country_code' => '+965'],
            ['country_name' => 'Kyrgyzstan', 'phone_country_code' => '+996'],
            ['country_name' => 'Laos', 'phone_country_code' => '+856'],
            ['country_name' => 'Latvia', 'phone_country_code' => '+371'],
            ['country_name' => 'Lebanon', 'phone_country_code' => '+961'],
            ['country_name' => 'Lesotho', 'phone_country_code' => '+266'],
            ['country_name' => 'Liberia', 'phone_country_code' => '+231'],
            ['country_name' => 'Libya', 'phone_country_code' => '+218'],
            ['country_name' => 'Liechtenstein', 'phone_country_code' => '+423'],
            ['country_name' => 'Lithuania', 'phone_country_code' => '+370'],
            ['country_name' => 'Luxembourg', 'phone_country_code' => '+352'],
            ['country_name' => 'Macedonia', 'phone_country_code' => '+389'],
            ['country_name' => 'Madagascar', 'phone_country_code' => '+261'],
            ['country_name' => 'Malawi', 'phone_country_code' => '+265'],
            ['country_name' => 'Malaysia', 'phone_country_code' => '+60'],
            ['country_name' => 'Maldives', 'phone_country_code' => '+960'],
            ['country_name' => 'Mali', 'phone_country_code' => '+223'],
            ['country_name' => 'Malta', 'phone_country_code' => '+356'],
            ['country_name' => 'Mauritania', 'phone_country_code' => '+222'],
            ['country_name' => 'Mauritius', 'phone_country_code' => '+230'],
            ['country_name' => 'Mexico', 'phone_country_code' => '+52'],
            ['country_name' => 'Micronesia', 'phone_country_code' => '+691'],
            ['country_name' => 'Moldova', 'phone_country_code' => '+373'],
            ['country_name' => 'Monaco', 'phone_country_code' => '+377'],
            ['country_name' => 'Mongolia', 'phone_country_code' => '+976'],
            ['country_name' => 'Montenegro', 'phone_country_code' => '+382'],
            ['country_name' => 'Morocco', 'phone_country_code' => '+212'],
            ['country_name' => 'Mozambique', 'phone_country_code' => '+258'],
            ['country_name' => 'Myanmar', 'phone_country_code' => '+95'],
            ['country_name' => 'Namibia', 'phone_country_code' => '+264'],
            ['country_name' => 'Nepal', 'phone_country_code' => '+977'],
            ['country_name' => 'Netherlands', 'phone_country_code' => '+31'],
            ['country_name' => 'New Zealand', 'phone_country_code' => '+64'],
            ['country_name' => 'Nicaragua', 'phone_country_code' => '+505'],
            ['country_name' => 'Niger', 'phone_country_code' => '+227'],
            ['country_name' => 'Nigeria', 'phone_country_code' => '+234'],
            ['country_name' => 'North Korea', 'phone_country_code' => '+850'],
            ['country_name' => 'Norway', 'phone_country_code' => '+47'],
            ['country_name' => 'Oman', 'phone_country_code' => '+968'],
            ['country_name' => 'Pakistan', 'phone_country_code' => '+92'],
            ['country_name' => 'Panama', 'phone_country_code' => '+507'],
            ['country_name' => 'Papua New Guinea', 'phone_country_code' => '+675'],
            ['country_name' => 'Paraguay', 'phone_country_code' => '+595'],
            ['country_name' => 'Peru', 'phone_country_code' => '+51'],
            ['country_name' => 'Philippines', 'phone_country_code' => '+63'],
            ['country_name' => 'Poland', 'phone_country_code' => '+48'],
            ['country_name' => 'Portugal', 'phone_country_code' => '+351'],
            ['country_name' => 'Qatar', 'phone_country_code' => '+974'],
            ['country_name' => 'Romania', 'phone_country_code' => '+40'],
            ['country_name' => 'Russia', 'phone_country_code' => '+7'],
            ['country_name' => 'Rwanda', 'phone_country_code' => '+250'],
            ['country_name' => 'Samoa', 'phone_country_code' => '+685'],
            ['country_name' => 'San Marino', 'phone_country_code' => '+378'],
            ['country_name' => 'Saudi Arabia', 'phone_country_code' => '+966'],
            ['country_name' => 'Senegal', 'phone_country_code' => '+221'],
            ['country_name' => 'Serbia', 'phone_country_code' => '+381'],
            ['country_name' => 'Seychelles', 'phone_country_code' => '+248'],
            ['country_name' => 'Sierra Leone', 'phone_country_code' => '+232'],
            ['country_name' => 'Singapore', 'phone_country_code' => '+65'],
            ['country_name' => 'Slovakia', 'phone_country_code' => '+421'],
            ['country_name' => 'Slovenia', 'phone_country_code' => '+386'],
            ['country_name' => 'Solomon Islands', 'phone_country_code' => '+677'],
            ['country_name' => 'Somalia', 'phone_country_code' => '+252'],
            ['country_name' => 'South Africa', 'phone_country_code' => '+27'],
            ['country_name' => 'South Korea', 'phone_country_code' => '+82'],
            ['country_name' => 'South Sudan', 'phone_country_code' => '+211'],
            ['country_name' => 'Spain', 'phone_country_code' => '+34'],
            ['country_name' => 'Sri Lanka', 'phone_country_code' => '+94'],
            ['country_name' => 'Sudan', 'phone_country_code' => '+249'],
            ['country_name' => 'Suriname', 'phone_country_code' => '+597'],
            ['country_name' => 'Swaziland', 'phone_country_code' => '+268'],
            ['country_name' => 'Sweden', 'phone_country_code' => '+46'],
            ['country_name' => 'Switzerland', 'phone_country_code' => '+41'],
            ['country_name' => 'Syria', 'phone_country_code' => '+963'],
            ['country_name' => 'Taiwan', 'phone_country_code' => '+886'],
            ['country_name' => 'Tajikistan', 'phone_country_code' => '+992'],
            ['country_name' => 'Tanzania', 'phone_country_code' => '+255'],
            ['country_name' => 'Thailand', 'phone_country_code' => '+66'],
            ['country_name' => 'Timor-Leste', 'phone_country_code' => '+670'],
            ['country_name' => 'Togo', 'phone_country_code' => '+228'],
            ['country_name' => 'Tonga', 'phone_country_code' => '+676'],
            ['country_name' => 'Trinidad and Tobago', 'phone_country_code' => '+1'],
            ['country_name' => 'Tunisia', 'phone_country_code' => '+216'],
            ['country_name' => 'Turkey', 'phone_country_code' => '+90'],
            ['country_name' => 'Turkmenistan', 'phone_country_code' => '+993'],
            ['country_name' => 'Tuvalu', 'phone_country_code' => '+688'],
            ['country_name' => 'Uganda', 'phone_country_code' => '+256'],
            ['country_name' => 'Ukraine', 'phone_country_code' => '+380'],
            ['country_name' => 'United Arab Emirates', 'phone_country_code' => '+971'],
            ['country_name' => 'United Kingdom', 'phone_country_code' => '+44'],
            ['country_name' => 'United States', 'phone_country_code' => '+1'],
            ['country_name' => 'Uruguay', 'phone_country_code' => '+598'],
            ['country_name' => 'Uzbekistan', 'phone_country_code' => '+998'],
            ['country_name' => 'Vanuatu', 'phone_country_code' => '+678'],
            ['country_name' => 'Vatican City', 'phone_country_code' => '+379'],
            ['country_name' => 'Venezuela', 'phone_country_code' => '+58'],
            ['country_name' => 'Vietnam', 'phone_country_code' => '+84'],
            ['country_name' => 'Yemen', 'phone_country_code' => '+967'],
            ['country_name' => 'Zambia', 'phone_country_code' => '+260'],
            ['country_name' => 'Zimbabwe', 'phone_country_code' => '+263'],
        ];
        

        foreach ($data as $record) {
            DB::table('phone_country_codes')->insert($record);
        }
    }
}
